services:
  backend:
    container_name: jares-backend-api
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /jares
    command: uvicorn src.main:app --host 0.0.0.0 --port 8080
    ports:
      - 8887:8080
    depends_on:
      database:
        condition: service_healthy
      
  database:
    container_name: jares-db-postgres
    image: postgres:alpine
    volumes:
      - psql-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}" ]
      interval: 4s
      timeout: 5s
      retries: 5
    
volumes:
  psql-data:
    driver: local
    name: psql-data
    driver_opts:
      type: none
      o: bind
      device: $PWD/db-data

networks:
  jares-network:
    name: jares-network
    driver: bridge
