"""modify language_models prompt columns to array

Revision ID: 04e1f199a420
Revises: 96095ce5879c
Create Date: 2024-12-12 10:38:22.454901

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "04e1f199a420"
down_revision: Union[str, None] = "96095ce5879c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "language_models", sa.Column("prompt", sa.ARRAY(sa.Text()), nullable=True)
    )
    op.drop_column("language_models", "prompt_3")
    op.drop_column("language_models", "prompt_2")
    op.drop_column("language_models", "prompt_1")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "language_models",
        sa.Column("prompt_1", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "language_models",
        sa.Column("prompt_2", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "language_models",
        sa.Column("prompt_3", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.drop_column("language_models", "prompt")
    # ### end Alembic commands ###
