"""new

Revision ID: 0a135ba5781d
Revises: f587eede2f22
Create Date: 2024-12-17 15:21:55.686083

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "0a135ba5781d"
down_revision: Union[str, None] = "f587eede2f22"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
