"""modify language_models column prompt to prompts

Revision ID: 2662545c7130
Revises: 04e1f199a420
Create Date: 2024-12-12 10:58:20.293789

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2662545c7130"
down_revision: Union[str, None] = "04e1f199a420"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "language_models", sa.Column("name", sa.String(length=50), nullable=False)
    )
    op.add_column(
        "language_models", sa.Column("prompts", sa.ARRAY(sa.Text()), nullable=True)
    )
    op.drop_column("language_models", "prompt")
    op.drop_column("language_models", "model_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "language_models",
        sa.Column(
            "model_name", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "language_models",
        sa.Column(
            "prompt", postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("language_models", "prompts")
    op.drop_column("language_models", "name")
    # ### end Alembic commands ###
