"""add unique constraint and modify column name group_name to name

Revision ID: 3af41f9cf76e
Revises: a98b0554f74a
Create Date: 2024-12-10 14:13:18.036857

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3af41f9cf76e"
down_revision: Union[str, None] = "a98b0554f74a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("groups", "group_name", nullable=False, new_column_name="name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "groups",
        sa.Column(
            "group_name", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "groups", type_="unique")
    op.create_unique_constraint("groups_group_name_key", "groups", ["group_name"])
    op.drop_column("groups", "name")
    # ### end Alembic commands ###
