"""rename models to llms

Revision ID: 3cb4d5bafc77
Revises: 579705476cec
Create Date: 2024-11-28 14:39:34.766487

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3cb4d5bafc77"
down_revision: Union[str, None] = "579705476cec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llms",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("model_name", sa.String(length=50), nullable=False),
        sa.Column("reference_file", sa.Text(), nullable=True),
        sa.Column("main_goals", sa.Text(), nullable=True),
        sa.Column("prompt_1", sa.Text(), nullable=True),
        sa.Column("prompt_2", sa.Text(), nullable=True),
        sa.Column("prompt_3", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_constraint("routines_model_id_fkey", "routines", type_="foreignkey")
    op.drop_table("models")
    op.create_foreign_key(None, "routines", "llms", ["model_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "routines", type_="foreignkey")
    op.create_foreign_key(
        "routines_model_id_fkey", "routines", "models", ["model_id"], ["id"]
    )
    op.create_table(
        "models",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "model_name", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column("reference_file", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("main_goals", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("prompt_1", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("prompt_2", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("prompt_3", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="models_pkey"),
    )
    op.drop_table("llms")
    # ### end Alembic commands ###
