"""group name be unique str

Revision ID: 4bde63fb0818
Revises: c5b31a5d4161
Create Date: 2024-12-05 12:22:00.666078

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4bde63fb0818"
down_revision: Union[str, None] = "c5b31a5d4161"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "groups", ["group_name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "groups", type_="unique")
    # ### end Alembic commands ###
