"""modify table

Revision ID: 579705476cec
Revises: a2820b4961eb
Create Date: 2024-11-28 14:20:39.407677

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "579705476cec"
down_revision: Union[str, None] = "a2820b4961eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "answers",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint("answers_survey_id_fkey", "answers", type_="foreignkey")
    op.drop_column("answers", "survey_id")
    op.add_column("questions", sa.Column("survey_id", sa.Integer(), nullable=False))
    op.add_column(
        "questions",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_foreign_key(None, "questions", "surveys", ["survey_id"], ["id"])
    op.create_foreign_key(None, "surveys", "questions", ["question_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "surveys", type_="foreignkey")
    op.drop_constraint(None, "questions", type_="foreignkey")
    op.drop_column("questions", "created_at")
    op.drop_column("questions", "survey_id")
    op.add_column(
        "answers",
        sa.Column("survey_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "answers_survey_id_fkey", "answers", "surveys", ["survey_id"], ["id"]
    )
    op.alter_column(
        "answers",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###
