"""new

Revision ID: 84397c4d6138
Revises: 8ddc99311924
Create Date: 2024-12-17 16:51:11.370226

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "84397c4d6138"
down_revision: Union[str, None] = "8ddc99311924"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
