"""new

Revision ID: 8ddc99311924
Revises: 840ca8a6a488
Create Date: 2024-12-17 16:49:52.851916

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "8ddc99311924"
down_revision: Union[str, None] = "840ca8a6a488"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
