"""modify llms table

Revision ID: 96095ce5879c
Revises: 3af41f9cf76e
Create Date: 2024-12-12 09:39:16.202568

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "96095ce5879c"
down_revision: Union[str, None] = "3af41f9cf76e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "language_models",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("model_name", sa.String(length=50), nullable=False),
        sa.Column("reference_file", sa.Text(), nullable=True),
        sa.Column("main_goals", sa.Text(), nullable=True),
        sa.Column("prompt_1", sa.Text(), nullable=True),
        sa.Column("prompt_2", sa.Text(), nullable=True),
        sa.Column("prompt_3", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table(
        "llms",
    )
    # op.create_unique_constraint(None, 'contacts', ['phone'])
    # op.create_unique_constraint(None, 'crops', ['name'])
    op.add_column(
        "routines", sa.Column("language_model_id", sa.Integer(), nullable=False)
    )
    op.add_column("routines", sa.Column("name", sa.String(length=50), nullable=False))
    # op.drop_constraint('routines_model_id_fkey', 'routines', type_='foreignkey')
    op.create_foreign_key(
        None, "routines", "language_models", ["language_model_id"], ["id"]
    )
    op.drop_column("routines", "routine_name")
    op.drop_column("routines", "model_id")
    op.drop_column("routines", "start_time")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "routines",
        sa.Column("start_time", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "routines",
        sa.Column("model_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "routines",
        sa.Column(
            "routine_name", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "routines", type_="foreignkey")
    op.create_foreign_key(
        "routines_model_id_fkey", "routines", "llms", ["model_id"], ["id"]
    )
    op.drop_column("routines", "name")
    op.drop_column("routines", "language_model_id")
    op.drop_constraint(None, "crops", type_="unique")
    op.drop_constraint(None, "contacts", type_="unique")
    op.create_table(
        "llms",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "model_name", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column("reference_file", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("main_goals", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("prompt_1", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("prompt_2", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("prompt_3", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="llms_pkey"),
    )
    op.drop_table("language_models")
    # ### end Alembic commands ###
