"""new

Revision ID: 9e65f26488a1
Revises: 84397c4d6138
Create Date: 2024-12-17 16:52:23.202437

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "9e65f26488a1"
down_revision: Union[str, None] = "84397c4d6138"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
