"""modify contact_groups table

Revision ID: a98b0554f74a
Revises: fdea3190eb89
Create Date: 2024-12-05 14:52:30.815372

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a98b0554f74a"
down_revision: Union[str, None] = "fdea3190eb89"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("contacts_group_id_fkey", "contacts", type_="foreignkey")
    op.drop_column("contacts", "group_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contacts",
        sa.Column("group_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "contacts_group_id_fkey", "contacts", "groups", ["group_id"], ["id"]
    )
    # ### end Alembic commands ###
