"""rename call_time to preferred_call_time

Revision ID: c5b31a5d4161
Revises: 0c69d861ae66
Create Date: 2024-12-04 17:43:47.677740

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c5b31a5d4161"
down_revision: Union[str, None] = "0c69d861ae66"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contacts", sa.Column("preferred_call_time", sa.Text(), nullable=True)
    )
    op.drop_column("contacts", "call_time")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contacts",
        sa.Column("call_time", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.drop_column("contacts", "preferred_call_time")
    # ### end Alembic commands ###
