"""new

Revision ID: cd74ab786b4e
Revises: 9e65f26488a1
Create Date: 2024-12-18 17:12:46.860970

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cd74ab786b4e"
down_revision: Union[str, None] = "9e65f26488a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("name", sa.String(length=50), nullable=False))
    op.drop_constraint("users_username_key", "users", type_="unique")
    op.create_unique_constraint(None, "users", ["name"])
    op.drop_column("users", "username")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "username", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "users", type_="unique")
    op.create_unique_constraint("users_username_key", "users", ["username"])
    op.drop_column("users", "name")
    # ### end Alembic commands ###
