"""new

Revision ID: f286c6927872
Revises: faecd224abd0
Create Date: 2024-12-17 16:27:57.566219

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "f286c6927872"
down_revision: Union[str, None] = "faecd224abd0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
