"""new

Revision ID: f587eede2f22
Revises: dbd46ed6fd9c
Create Date: 2024-12-17 15:17:53.918412

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f587eede2f22"
down_revision: Union[str, None] = "dbd46ed6fd9c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "routines",
        sa.Column("excution_days", sa.ARRAY(sa.String(length=3)), nullable=False),
    )
    op.add_column("routines", sa.Column("execution_count", sa.Integer(), nullable=True))
    op.drop_column("routines", "day_of_the_week")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "routines",
        sa.Column(
            "day_of_the_week",
            sa.VARCHAR(length=20),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("routines", "execution_count")
    op.drop_column("routines", "excution_days")
    # ### end Alembic commands ###
