"""new

Revision ID: faecd224abd0
Revises: 0a135ba5781d
Create Date: 2024-12-17 15:22:08.281361

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "faecd224abd0"
down_revision: Union[str, None] = "0a135ba5781d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "routines",
        sa.Column("execution_days", sa.ARRAY(sa.String(length=3)), nullable=False),
    )
    op.drop_column("routines", "excution_days")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "routines",
        sa.Column(
            "excution_days",
            postgresql.ARRAY(sa.VARCHAR(length=3)),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("routines", "execution_days")
    # ### end Alembic commands ###
