"""modify contact_groups table

Revision ID: fdea3190eb89
Revises: 4bde63fb0818
Create Date: 2024-12-05 14:48:27.506823

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fdea3190eb89"
down_revision: Union[str, None] = "4bde63fb0818"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("contact_groups", sa.Column("group_id", sa.Integer(), nullable=False))
    op.drop_constraint(
        "contact_groups_crop_id_fkey", "contact_groups", type_="foreignkey"
    )
    op.create_foreign_key(None, "contact_groups", "groups", ["group_id"], ["id"])
    op.drop_column("contact_groups", "crop_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contact_groups",
        sa.Column("crop_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "contact_groups", type_="foreignkey")
    op.create_foreign_key(
        "contact_groups_crop_id_fkey", "contact_groups", "crops", ["crop_id"], ["id"]
    )
    op.drop_column("contact_groups", "group_id")
    # ### end Alembic commands ###
